### ISSUE TITLE
Upgrade socket.io

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#173]
We should likely upgrade to Socket.io 4.x since versions 2.x and 3.x are no longer actively maintained [1] [2]. This repo uses socket.io 2.1.

It's unclear if there are any breaking changes with this upgrade due to the `clusterserver.js` dependency on `socketio-sticky-sessions` which is on v0.4.3 and has not been updated for 4 years.

[1] https://socket.io/docs/v2/
[2] https://socket.io/docs/v3/

**Comment by tzfx** [comment]
Agreed #124 :)

**Comment by tzfx** [comment]
The starter should now be upgraded to 4. I've kept 2/3 compatibility switched on until we find the time to upgrade the ngx-starter client side up to 4. The client doesn't appear to be affected by the security issue, but it would be good to have them both in sync.
