### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#193]
TypeScript would increase maintainability, decrease new developer onboarding, and allow for shared model classes between the Angular UI and Node.js API.

To reduce the burden of migrating to TypeScript, the app should support `.ts` and `.js` files simultaneously. This would allow forks to upgrade safely and at their own pace.

Idea proposed by @gu. Supported by @jrassa @tzfx and @brianghig

**Comment by gu** [comment]
@brianghig Current set of in-progress changes are here if you wanna take a peek

https://github.com/gu/node-rest-starter/tree/feat/typescript

**Comment by brianghig** [comment]
Resolved by @gu via #194
