### ISSUE TITLE
Convert Teams module to TypeScript

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#204]
The Teams module contains code critical for managing team members and a team's access to resources in the application. By converting it to TypeScript, downstream forks can more easily verify compatibility with updates to the starter's Teams module.

**Comment by jrassa** [comment]
One interesting challenge here is the way the user/teams schemas are defined.  `team.model.js` creates a modified version of the User Schema, adding the teams array.  The result is that we have two models we can use to look up Users, `User` and `TeamUser`.  If you use `User`, you won't get the team array.  If you user 'TeamUser` you will get the team array.

I would suggest that we clean this up and condense these 2 models into 1 and define the team array directly on the User model.

**Comment by jrassa** [comment]
Initial work on this covered by #227.  Once that is merged, the rest of the module can be converted.

**Comment by jrassa** [comment]
Closed via #235
