### ISSUE TITLE
Remove getter on Date fields in mongoose models

### ISSUE THREAD

**Issue by jrassa** [bluehalo/node-rest-starter#207]
Currently, most/all date fields defined on mongoose models are defined as:

```js
created: {
	type: Date,
	default: () => Date.now(),
	get: util.dateParse
}
```

The getter converts the date value to a numeric epoch value vs. an actual JS Date object.  When combined with use of the GetterPlugin, date values are also returned the same in JSON returned to client.  Without the getters, Dates in returned JSON would be converted to an ISO 8601 string (i.e. `2022-08-31T17:39:20.824Z`).

I did some quick testing on the User and Feedback models and removing the getter doesn't seem to cause any issues.  The UI still handles rendering the dates properly.

Another added benefit of removing the getters, is that it will allow us to use mongoose's  [timestamps feature](https://mongoosejs.com/docs/timestamps.html) option.  When using this, mongoose will automatically create the created and updated fields on schema as well as automatically handle setting values when appropriate.  This will be especially helpful for updates as currently we are manually setting a new updated date.

**Comment by eacaps** [comment]
I've updated the models to remove `get: util.dateParse` and tested it out with ngx-starter and all seems well, the dates are returned as iso dates as indicated above. There are some broken tests now so I'm sorting through those then updating to use the timestamps feature.

**Comment by eacaps** [comment]
They say you learn something new everyday and today I learned:
```
new Date(1663016705996) === new Date(1663016705996)
false
```
I suppose that is object comparison at work...
