### ISSUE TITLE
Convert Audit module to TS

### ISSUE THREAD

**Issue by jrassa** [bluehalo/node-rest-starter#228]
Conversion should mostly straight forward.  Check existing ts code for examples.

The difficult part is that there is a bit of race condition that exists with `audit.service.js` due to its inclusion in `dependencies.js`.  Currently, audit service is initially created when first reference by `dependencies.js`.  This occurs before mongoose has loaded all of the models.  To account for this, unlike other service classes, `audit.service.js` defers accessing the user and audit models until they are actually needed.

This deferred lookup could be maintained when migrating to typescript.  But ideally we would refactor things to ensure that this is not an issue.  The simple approach, would be to just remove `audit.service.js` from `dependencies.js` and have files that depend on it to import it directly.  The alternative approach, would be to ensure that all the models have to been loaded by mongoose before `dependencies.js` is loaded.

**Comment by jrassa** [comment]
Another option that I have been considering is to use an event emitter to decouple the auditing from the actual implementation.  Doing so, `dependencies.js` would have an audit service that simply publishes the audit event details to an event emitter.  Then a separate implementation audit service would subscribe to the event emitter and process the audit events appropriately (i.e. write to mongo, log to audit log file).

**Comment by bgdoyle** [comment]
@jrassa I'm a fan of the event-driven implementation, but I think that's a bit beyond the scope of this issue.

I can take a look at making the necessary Typescript changes, and I'll maintain the deferred lookup for now.
