### ISSUE TITLE
Separate "feedback" from "audit"

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#4]
At the moment, the Feedback entries are submitted through Audit routes in Express and stored co-mingled in the "audit" DB collection. This makes them slower to query with a large audit log, and requires full auditor privileges in order to view that Feedback.

Possible updates:

- Move all "feedback" routes to the feedback module
- Move "feedback" records into their own collection

**Comment by reblace** [comment]
I vote we do both. We could look for ways to generify it. But, it'd be good to break it out.

**Comment by jrassa** [comment]
I can take a stab at this.  I have been working on moving over the UI portions.

**Comment by brianghig** [comment]
Sounds good @jrassa ! I’m working on some admin UI features to complement these service endpoints, so I’ll hold off on Feedback for now and I’ll make sure it’s all being tracked in other issues.

**Comment by brianghig** [comment]
Resolved via #8
