### ISSUE TITLE
Manage scheduled jobs with concurrency

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#45]
In order to improve application functionality across multiple instances of the node-rest-starter application, we should refactor scheduled jobs (like the user cache refresh) to support either single-instance or every-instance configurations.

For example, we only want one instance in our cluster to refresh the user credentials cache, and we do not care which instance in the cluster performs that job. On the other hand, if every instance needs to "check in" with a health monitoring system, we would want to run that on all of them.

**Comment by jrassa** [comment]
Our newer Agenda.js based scheduling system supports this.  See #183.
