### ISSUE TITLE
Consolidate Promise implementation

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#7]
There seems to be a combination of native promises and the Q library, along with forks leveraging Bluebird.

I'd recommend that we settle on one Promise implementation and use it consistently.

**Comment by brianghig** [comment]
@ymao1 @mheir @reblace @lu-c @matthewgaulin @jrassa et al. ...
my preference is to use native Promises and remove dependencies on Q and Bluebird elsewhere. That does take away some of the features of those third-party Promise libraries, like `Promise.join`, but that seems to be an acceptable trade-off when there are workarounds and it can reduce our overall dependency footprint.

**Comment by reblace** [comment]
I've tried to move towards using native promises. Like you said, some of the helper functions go away when you make that decision, but it consolidates things and removes extraneous dependencies.

**Comment by jrassa** [comment]
I agree.  I've also been moving towards using async await which removes a lot of need to use promises in general.

**Comment by reblace** [comment]
Something to track as part of this is that we've got Mongoose configured to use q I believe. We'll need to remove that config to get it to go back to using native promises. Then, there's a lot of refactoring to remove all the calls to done().
