### ISSUE TITLE
Upgrade ecmaVersion for eslint to 2020

### ISSUE THREAD

**Issue by brianghig** [bluehalo/node-rest-starter#74]
Current ECMA version of 8 maps to 2017, and does not include support for spread operators `{ ...foo, bar: 1 }` and other items supported with the latest LTS version of Node.js.

**Comment by jrassa** [comment]
We should keep this aligned with [targeted version of node](https://github.com/Asymmetrik/node-rest-starter/blob/develop/package.json#L11).  We are still targeting node 8, which is no longer supported.

**Comment by brianghig** [comment]
@jrassa Good looking out! v12 is current LTS. Any objections to targeting v12, at least until October when v14 becomes active LTS?

https://nodejs.org/en/about/releases/

**Comment by jrassa** [comment]
No objections.  I'm still running on v10, but have been planning to upgrade.  Based on [this](https://node.green/#ES2020), we should set ecmaVersion to 2019 when upgrading to v12.  The see how feature support is when v14 is ready.
