### ISSUE TITLE
End User Agreement (EUA) Feature

### ISSUE THREAD

**Issue by cj-asymmetrik** [bluehalo/node-rest-starter#90]
**Current Status**

Once you read and acknowledge the EUA for the first time in the app, it doesn't show up again unless it is either updated + published or a new EUA is created + published.

Use the following path: Admin > Users list, you should be able to add the EUA column to see who's accepted that agreement.

**Desired Status**

Agreements should remain accessible. Once the user accepts then they should still be able to access the item they just read for their reference.  Any updates we make to that could show up there and a notification icon would alert the user of changes. We would display any updates with a timestamp. Make the current EUA available for viewing at any time by users; possibly under the help nav, "show EUA" or something that allows them to view the text in a modal.

**Comment by brianghig** [comment]
@cj-asymmetrik I'm going to close this and open up a ticket on the `ngx-starter` project that contains the user interface for these starter apps.

**Comment by brianghig** [comment]
Recreated at https://github.com/Asymmetrik/ngx-starter/issues/160
